name: skywatch
description: A Flutter weather application using OpenWeatherMap.
publish_to: "none"
version: 1.0.0+1
author: Aqeela

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  dio: ^5.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  geolocator: ^14.0.2
  syncfusion_flutter_charts: ^31.2.18
  lottie: ^3.2.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/animations/sunny.json
